site_url: https://poltexious.github.io/undervisning/
site_name: Undervisning – Jakob Polcwiartek

theme:
  name: material
  language: da
  logo: assets/images/aatg-logo-hvid.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
theme:
  name: material
  language: da
  logo: assets/images/aatg-logo-hvid.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Skift til light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Skift til dark mode

copyright: "© BUILD_YEAR Jakob Polcwiartek"

extra:
  homepage: https://aatg.dk/studieretninger/gametech/
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/logo-link.js
  - javascripts/fag-farver.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Forside: index.md
  - Matematik: matematik/index.md
  - Fysik: fysik/index.md
  - Programmering B:
      - Oversigt: programmering-b/index.md
      - 1.g:
          - Overblik: programmering-b/1g/index.md
          - F01 Intro, værktøjer & logbog: programmering-b/1g/f01_intro_logbog.md
          - F02 Basics & kontrolstrukturer: programmering-b/1g/f02_basics_kontrol.md
          - F03 Metoder & dekomponering: programmering-b/1g/f03_metoder_dekomponering.md
          - F04 Arrays, lister & algoritmer: programmering-b/1g/f04_arrays_lister_algoritmer.md
          - F05 OOP light: programmering-b/1g/f05_oop_light.md
          - "F06 Mini-projekt: konsolspil": programmering-b/1g/f06_miniprojekt_konsolspil.md
      - 2.g: programmering-b/2g.md
      - 3.g: programmering-b/3g.md