site_url: https://poltexious.github.io/undervisning/
site_name: Undervisning – Jakob Polcwiartek

theme:
  name: material
  language: da
  logo: assets/images/aatg-logo-hvid.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Skift til dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Skift til light mode

copyright: "© BUILD_YEAR Jakob Polcwiartek"

extra:
  homepage: https://aatg.dk/studieretninger/gametech/
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/logo-link.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Forside: index.md
  - Programmering B:
      - Oversigt: programmering-b/index.md
      - 1.g: programmering-b/1g.md
      - 2.g: programmering-b/2g.md
      - 3.g: programmering-b/3g.md
  - Matematik: matematik/index.md
  - Fysik: fysik/index.md